# numpy


In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
array1 = np.array([1,1])
print(array1) #single diamention array
print(array1.ndim)

[1 1]
1


In [13]:
array2 = np.array([[1,1],[2,2]])
print(array2) #doul diamention array
print(array2.ndim)

[[1 1]
 [2 2]]
2


In [17]:
array3 = np.array([[1,1,2],[2,2,3],[3,3,4]])
print(array3.shape) #(row, column)
print(array3.ndim) #array dim
print(array3.size) #total elements

(3, 3)
2
9


In [22]:
#To find shape , size of array - 

import numpy as np

array3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

print(array3.shape) # rows,column

print(array3.size) #total elements

print(array3.ndim) #array dim

(1, 3, 3)
9
3


In [24]:
a = ([1,2,3,4,5])
print(a[2])

3


In [34]:
#array indexing
array2 = np.array([[1,3],[2,4]])
print(array2[1,1]) #row, column

4


In [37]:
array2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(array2.ndim)
print(array2.shape)
print(array2.size)
print(array2[2,2])
print(array2[0,3])

2
(4, 4)
16
11
4


In [24]:
#index array[start : stop : step]

array3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
#array3[0:2,1:3]
# print (array3[0,0])
# print (array3[0,1])
# print (array3[0,2])
# print (array3[0,3])
#print (array3[0:1,0:4])
print (array3[0])
print (array3[1])
print (array3[2])
print (array3[3])

#array3[0:1,1:1]

#print(array3.shape)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]


In [26]:
#Special functions in numpy

np.zeros((2,3))     # all zeros
# np.ones((2,2))      # all ones
# np.arange(0,10,2)   # [0,2,4,6,8]
# np.linspace(0,1,5)  # 5 evenly spaced values

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.ones((2,2))      # all ones

array([[1., 1.],
       [1., 1.]])

In [30]:
np.arange(0,10,2)   # [0,2,4,6,8]

array([0, 2, 4, 6, 8])

In [31]:
np.linspace(0,1,5)  # 5 evenly spaced values

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [32]:
#oprators

a = np.array ([1,2,3,4])
b = np.array ([4,5,3,4])
print (a+b)
print (a*b)

[5 7 6 8]
[ 4 10  9 16]


In [55]:
#boolean index

print (a[a>2])
print (b[b<2])

[3 4 5 4 5]
[]


In [41]:
#data types array

a = np.array ([1,2,3,4], dtype=float)
print(a)

[1. 2. 3. 4.]


In [45]:
#math function

a = np.array ([1,2,3,4])
print(np.square(a))

[ 1  4  9 16]


In [51]:
#statics function

a = np.array([1,2,3,4,5,4,5])
print(np.mean(a))     # average
print(np.median(a))
print(np.std(a))      # standard deviation
print(np.sum(a))
print(np.min(a))
print(np.max(a))
# print(np.mod(a))

3.4285714285714284
4.0
1.3997084244475304
24
1
5
